services:
  init-kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: init-kafka
    depends_on:
      - kafka
    entrypoint: /bin/sh
    command:
      - -c
      - |
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic transferencia-topic --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic tarifa-topic --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic usuario-topic --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic contacorrente-topic --partitions 1 --replication-factor 1
